import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'

import { Inter } from 'next/font/google'

import { ThemeTogglerProvider } from '@/providers/ThemeTogglerP';
import { NavbarContainer } from '@/containers/Navbar/NavbarContainer';

import './reset.css'

//#region msw
//keep this region commented for production
// TODO: Instead of commenting code, before building, remove this region programmatically
/* import { MSWServer } from '../msw/Server'

if(process.env.IS_MSW_ON && process.env.NODE_ENV === 'development' && typeof window === 'undefined'){
  MSWServer.init();
} */
//#endregion


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeTogglerProvider>
            <NavbarContainer />
            {children}
          </ThemeTogglerProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
